name: Metrics
on:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # AniList plugin
          plugin_anilist: yes
          plugin_anilist_medias: anime
          plugin_anilist_user: rekka69
          plugin_anilist_sections: favorites, watching
          plugin_anilist_limit: 4
