name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: Metrics
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
  anilist:
      runs-on: ubuntu-latest
      environment: 
        name: Metrics
      permissions:
        contents: write
      steps:
        - uses: lowlighter/metrics@latest
          with:
            filename: metrics.anilist.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: ""
            plugin_anilist: yes
            plugin_anilist_medias: anime
            plugin_anilist_user: rekka69
            plugin_anilist_sections: favorites, characters
            plugin_anilist_limit: 5
            plugin_anilist_limit_characters: 5

      

